# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 3000, host: 3000
  # config.vm.network "private_network", type: "dhcp"

  # config.vm.network "private_network", ip: "192.168.0.5"

  config.vm.hostname = "movie-catalog"

  config.vm.synced_folder "../", "/home/ubuntu/MovieCatalog"

  config.vm.post_up_message = "WorkSpace project dev server successfuly started.
    Connect to host with: http://l92.168.0.5:3000/ or over ssh with `vagrant ssh`"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "movie-catalog"
    vb.memory = "1024"
    vb.cpus = "1"
  end

  # config.vm.provision :shell, path: "bootstrap.sh"

  # config.vm.provision :shell, path: "start_application.sh", run: "always", privileged: false
end